version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "45432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "53603:53603"
      - "48080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root

  zookeeper:
    image: 'strimzi/kafka:0.20.1-kafka-2.6.0'
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: 'strimzi/kafka:0.20.1-kafka-2.6.0'
    command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties
        --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
        --override listeners=$${KAFKA_LISTENERS}
        --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS}
        --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,AKHQ://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,AKHQ://kafka:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,AKHQ:PLAINTEXT
    links:
      - zookeeper

  akhq:
    image: 'tchiotludo/akhq:dev'
    ports:
      - '9000:8080'
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
    links:
      - kafka

  prometheus:
    image: "prom/prometheus"
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml