global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'quarkus-bootcamp'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']