name: release-build-macos

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GraalVM
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.0.0.java11'

      - name: Install native-image
        run: gu install native-image

      - name: Cache local Maven repository
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set version
        run: ./mvnw --no-transfer-progress versions:set -DnewVersion="${{ github.event.release.tag_name }}"

      - name: Build native executable
        run: ./mvnw --no-transfer-progress package -Dnative

      - name: Upload native executable
        id: upload-native-executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/quarkus-bootcamp-${{ github.event.release.tag_name }}-runner
          asset_name: quarkus-bootcamp-${{ github.event.release.tag_name }}-macos
          asset_content_type: application/octet-stream
